sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - if node --version | grep -c v6 >/dev/null; then travis_start_sauce_connect; fi
script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run dist
  - if node --version | grep -c v6 >/dev/null; then export BUILD=`git rev-parse HEAD`; export NODE=`node --version`; npm run browser_test; fi
after_script:
  - if node --version | grep -c v6 >/dev/null; then travis_stop_sauce_connect; fi
addons:
  sauce_connect: true
