sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - echo 'begin tests'
script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run dist
  - if node --version | grep -c v6 >/dev/null; then npm run browser_test; fi
after_script:
  - echo "end tests"
addons:
  sauce_connect: true
