sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - echo "before_script"
script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run dist
  - npm run browser_test
after_script:
  - echo "after_script"
addons:
  sauce_connect: true
